-- Treesitter highlights
local c = require('colors.monokai.palette')

return {
  -- Treesitter highlighting (additional)
  TSAttribute = { fg = c.purple },
  TSBoolean = { fg = c.pink},
  TSCharacter = { fg = c.string },
  TSComment = { link = "Comment" },
  TSConditional = { fg = c.pink},
  TSConstant = { fg = c.blue_light, italic = true },
  TSConstBuiltin = { fg = c.blue_light, italic = true },
  TSConstMacro = { fg = c.blue_light, italic = true },
  TSConstructor = { fg = c.blue },
  TSError = { fg = c.error },
  TSException = { fg = c.blue_light, italic = true },
  TSField = { fg = c.fg },
  TSFloat = { link = "Float" },
  TSFunction = { fg = c.blue_light, italic = true },
  TSFuncBuiltin = { fg = c.blue_light, italic = true },
  TSFuncMacro = { fg = c.blue_light, italic = true },
  TSInclude = { fg = c.red},
  TSKeyword = { fg = c.red},
  TSKeywordFunction = { fg = c.blue_light, italic = true },
  TSKeywordOperator = { fg = c.blue_light, italic = true },
  TSKeywordReturn = { fg = c.red},
  TSLabel = { link = "Label" },
  TSMethod = { fg = c.green_light },
  TSNamespace = { fg = c.blue },
  TSNone = { fg = c.fg },
  TSNumber = { link = "Number" },
  TSOperator = { link = "Operator" },
  TSParameter = { fg = c.orange },
  TSParameterReference = { fg = c.orange },
  TSProperty = { fg = c.fg },
  TSPunctDelimiter = { fg = c.fg },
  TSPunctBracket = { fg = c.fg },
  TSPunctSpecial = { fg = c.pink },
  TSRepeat = { link = "Repeat" },
  TSString = { link = "String" },
  TSStringRegex = { fg = c.string },
  TSStringEscape = { fg = c.pink },
  TSStringSpecial = { fg = c.string },
  TSSymbol = { fg = c.purple },
  TSTag = { fg = c.pink },
  TSTagAttribute = { fg = c.orange },
  TSTagDelimiter = { fg = c.fg },
  TSText = { fg = c.fg },
  TSStrong = { bold = true },
  TSEmphasis = { italic = true },
  TSUnderline = { underline = true },
  TSStrike = { strikethrough = true },
  TSTitle = { fg = c.blue, bold = true },
  TSLiteral = { fg = c.string },
  TSURI = { fg = c.string, underline = true },
  TSMath = { fg = c.blue },
  TSTextReference = { fg = c.purple },
  TSEnvironment = { fg = c.pink },
  TSEnvironmentName = { fg = c.string },
  TSNote = { fg = c.info },
  TSWarning = { fg = c.warning },
  TSDanger = { fg = c.error },
  TSType = { link = "Type" },
  TSTypeBuiltin = { fg = c.blue },
  TSVariable = { fg = c.fg },
  TSVariableBuiltin = { fg = c.purple },
}
